# -*- coding: utf-8 -*-
"""stable_diffusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sS-yZxFjBUDIaDPEXBWZO2lDypYZzA_o
"""

!nvidia-smi

"""# diffusion model is text-image based model

# Project -1 :text - image
"""



#!pip install diffusers --upgrade

#pip install invisible_watermark transformers accelerate safetensors

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float32, use_safetensors=True, variant="fp16")
pipe.to("cuda")

# if using torch < 2.0
# pipe.enable_xformers_memory_efficient_attention()

prompt = "An astronaut riding a green horse"

images = pipe(prompt=prompt).images[0]

from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

image = pipe("An astronaut riding a green horse").images[0]

image.save("output.png")
image

import gradio as gr
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")


def generate(prompt, steps, guidance):
    image = pipe(
        prompt=prompt,
        num_inference_steps=steps,
        guidance_scale=guidance
    ).images[0]

    return image


with gr.Blocks(theme=gr.themes.Soft(), title="Stable Diffusion") as demo:

    gr.Markdown("# Stable Diffusion Image Generator")
    gr.Markdown("Generate images from text prompts.")

    with gr.Row():
        with gr.Column():
            prompt = gr.Textbox(
                label="Prompt",
                placeholder="A futuristic city at sunset..."
            )

            steps = gr.Slider(
                minimum=10,
                maximum=50,
                value=25,
                step=1,
                label="Inference Steps"
            )

            guidance = gr.Slider(
                minimum=1,
                maximum=15,
                value=7.5,
                step=0.5,
                label="Guidance Scale"
            )

            btn = gr.Button(" Generate Image")

        with gr.Column():
            output = gr.Image(label="Generated Image")

    btn.click(
        fn=generate,
        inputs=[prompt, steps, guidance],
        outputs=output
    )

demo.launch()